<a href="https://colab.research.google.com/github/josmimaria/Machine-Learning/blob/development/numpy_part_3_eng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Numpy - Array Manipulation.

In [10]:
arr = np.random.randint(1,10 , (4,4))

In [11]:
arr

array([[9, 8, 3, 2],
       [8, 7, 6, 7],
       [2, 5, 9, 5],
       [4, 1, 2, 9]])

In [12]:
arr.reshape(8,2)

array([[9, 8],
       [3, 2],
       [8, 7],
       [6, 7],
       [2, 5],
       [9, 5],
       [4, 1],
       [2, 9]])

In [13]:
arr

array([[9, 8, 3, 2],
       [8, 7, 6, 7],
       [2, 5, 9, 5],
       [4, 1, 2, 9]])

In [14]:
arr.T

array([[9, 8, 2, 4],
       [8, 7, 5, 1],
       [3, 6, 9, 2],
       [2, 7, 5, 9]])

In [14]:
arr

In [15]:
arr.flatten()

array([9, 8, 3, 2, 8, 7, 6, 7, 2, 5, 9, 5, 4, 1, 2, 9])

In [16]:
arr

array([[9, 8, 3, 2],
       [8, 7, 6, 7],
       [2, 5, 9, 5],
       [4, 1, 2, 9]])

In [17]:
arr.flatten()

array([9, 8, 3, 2, 8, 7, 6, 7, 2, 5, 9, 5, 4, 1, 2, 9])

In [18]:
arr

array([[9, 8, 3, 2],
       [8, 7, 6, 7],
       [2, 5, 9, 5],
       [4, 1, 2, 9]])

In [19]:
np.expand_dims(arr,axis=1)

array([[[9, 8, 3, 2]],

       [[8, 7, 6, 7]],

       [[2, 5, 9, 5]],

       [[4, 1, 2, 9]]])

In [20]:
np.expand_dims(arr,axis=0)

array([[[9, 8, 3, 2],
        [8, 7, 6, 7],
        [2, 5, 9, 5],
        [4, 1, 2, 9]]])

In [21]:
data = np.array([[1] , [2] , [3]])

In [22]:
np.squeeze(data)

array([1, 2, 3])

In [23]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [25]:
data

array([[1],
       [2],
       [3]])

In [28]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [30]:
np.diag(np.array([3,3,4]))

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [32]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [33]:
#Numpy - Binary Operators

In [34]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [35]:
arr1

array([[9, 4, 8, 5],
       [6, 5, 5, 2],
       [1, 1, 5, 5]])

In [36]:
arr2

array([[9, 8, 9, 3],
       [9, 6, 4, 7],
       [9, 3, 3, 9]])

In [37]:
arr1+arr2

array([[18, 12, 17,  8],
       [15, 11,  9,  9],
       [10,  4,  8, 14]])

In [38]:
arr1*arr2

array([[81, 32, 72, 15],
       [54, 30, 20, 14],
       [ 9,  3, 15, 45]])

In [39]:
arr1/arr2

array([[1.        , 0.5       , 0.88888889, 1.66666667],
       [0.66666667, 0.83333333, 1.25      , 0.28571429],
       [0.11111111, 0.33333333, 1.66666667, 0.55555556]])

In [40]:
arr1-arr2

array([[ 0, -4, -1,  2],
       [-3, -1,  1, -5],
       [-8, -2,  2, -4]])

In [41]:
arr1**arr2

array([[387420489,     65536, 134217728,       125],
       [ 10077696,     15625,       625,       128],
       [        1,         1,       125,   1953125]])

In [42]:
~arr1

array([[-10,  -5,  -9,  -6],
       [ -7,  -6,  -6,  -3],
       [ -2,  -2,  -6,  -6]])

In [43]:
arr1

array([[9, 4, 8, 5],
       [6, 5, 5, 2],
       [1, 1, 5, 5]])

In [44]:
arr2

array([[9, 8, 9, 3],
       [9, 6, 4, 7],
       [9, 3, 3, 9]])

In [45]:
arr1>arr2

array([[False, False, False,  True],
       [False, False,  True, False],
       [False, False,  True, False]])

In [ ]:
#Numpy - String Functions.

In [ ]:
arr = np.array(["sudh" , "kumar"])

In [ ]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [ ]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [ ]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [ ]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [ ]:
#Numpy - Mathematical Functions.

In [46]:
arr1

array([[9, 4, 8, 5],
       [6, 5, 5, 2],
       [1, 1, 5, 5]])

In [47]:
np.sin(arr1)

array([[ 0.41211849, -0.7568025 ,  0.98935825, -0.95892427],
       [-0.2794155 , -0.95892427, -0.95892427,  0.90929743],
       [ 0.84147098,  0.84147098, -0.95892427, -0.95892427]])

In [48]:
np.cos(arr1)

array([[-0.91113026, -0.65364362, -0.14550003,  0.28366219],
       [ 0.96017029,  0.28366219,  0.28366219, -0.41614684],
       [ 0.54030231,  0.54030231,  0.28366219,  0.28366219]])

In [49]:
np.tan(arr1)

array([[-0.45231566,  1.15782128, -6.79971146, -3.38051501],
       [-0.29100619, -3.38051501, -3.38051501, -2.18503986],
       [ 1.55740772,  1.55740772, -3.38051501, -3.38051501]])

In [50]:
np.log10(arr1)

array([[0.95424251, 0.60205999, 0.90308999, 0.69897   ],
       [0.77815125, 0.69897   , 0.69897   , 0.30103   ],
       [0.        , 0.        , 0.69897   , 0.69897   ]])

In [51]:
np.exp(arr1)

array([[8.10308393e+03, 5.45981500e+01, 2.98095799e+03, 1.48413159e+02],
       [4.03428793e+02, 1.48413159e+02, 1.48413159e+02, 7.38905610e+00],
       [2.71828183e+00, 2.71828183e+00, 1.48413159e+02, 1.48413159e+02]])

In [52]:
np.power(arr1,2)

array([[81, 16, 64, 25],
       [36, 25, 25,  4],
       [ 1,  1, 25, 25]])

In [53]:
np.mean(arr1
       )

np.float64(4.666666666666667)

In [54]:
np.median(arr1)

np.float64(5.0)

In [55]:
np.std(arr1)

np.float64(2.3570226039551585)

In [56]:
np.var(arr1)

np.float64(5.555555555555556)

In [57]:
np.min(arr1)

np.int64(1)

In [58]:
np.max(arr1)

np.int64(9)

In [ ]:
#Numpy - Arithmetic Operations.

In [59]:
arr1

array([[9, 4, 8, 5],
       [6, 5, 5, 2],
       [1, 1, 5, 5]])

In [60]:
arr2

array([[9, 8, 9, 3],
       [9, 6, 4, 7],
       [9, 3, 3, 9]])

In [61]:
arr1-arr2

array([[ 0, -4, -1,  2],
       [-3, -1,  1, -5],
       [-8, -2,  2, -4]])

In [62]:
np.subtract(arr1,arr2)

array([[ 0, -4, -1,  2],
       [-3, -1,  1, -5],
       [-8, -2,  2, -4]])

In [63]:
np.multiply(arr1,arr2)

array([[81, 32, 72, 15],
       [54, 30, 20, 14],
       [ 9,  3, 15, 45]])

In [64]:
np.mod(arr1,arr2)

array([[0, 4, 8, 2],
       [6, 5, 1, 2],
       [1, 1, 2, 5]])

In [66]:
np.power(arr1,arr2)

array([[387420489,     65536, 134217728,       125],
       [ 10077696,     15625,       625,       128],
       [        1,         1,       125,   1953125]])

In [67]:
np.sqrt(arr1)

array([[3.        , 2.        , 2.82842712, 2.23606798],
       [2.44948974, 2.23606798, 2.23606798, 1.41421356],
       [1.        , 1.        , 2.23606798, 2.23606798]])

In [68]:
#Numpy - Statistical Functions.

In [69]:
arr1

array([[9, 4, 8, 5],
       [6, 5, 5, 2],
       [1, 1, 5, 5]])

In [70]:
np.mean(arr1)

np.float64(4.666666666666667)

In [71]:
np.std(arr1)

np.float64(2.3570226039551585)

In [72]:
np.median(arr1)

np.float64(5.0)