<a href="https://colab.research.google.com/github/josmimaria/Machine-Learning/blob/development/Numpy_part_1_Eng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [7]:
arr.ndim

1

In [8]:
arr1.ndim

2

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
mat = np.matrix(l)

In [12]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [13]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
a = arr

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[0] = 100

In [19]:
arr

array([100,   2,   3,   4,   5])

In [20]:
a

array([100,   2,   3,   4,   5])

In [21]:
b = np.copy(arr)

In [22]:
b

array([100,   2,   3,   4,   5])

In [23]:
b[0] = 234

In [24]:
b

array([234,   2,   3,   4,   5])

In [25]:
arr

array([100,   2,   3,   4,   5])

In [26]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [29]:
iterable  = (i*i for i in range(5))

In [30]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('23 45 56',sep  = ' ' )

array([23., 45., 56.])

In [32]:
np.fromstring('23,45,56',sep  = ',' )

array([23., 45., 56.])

In [33]:
arr

array([100,   2,   3,   4,   5])

In [34]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [35]:
arr.ndim

1

In [36]:
arr1.ndim

2

In [37]:
arr.size

5

In [38]:
arr1.size

6

In [39]:
arr.shape

(5,)

In [40]:
arr1.shape

(2, 3)

In [41]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr1.dtype

dtype('int64')